import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "normalize.css";
import { Toaster } from "sonner";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className={inter.className}>
        <header className="text-gray-600 body-font">
          <div className="container mx-16 flex flex-wrap pt-8 flex-col md:flex-row items-center">
            <a className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
              <span className="text-xl">Next.js Example</span>
            </a>
            <nav className="md:ml-auto flex gap-8 flex-wrap items-center text-base justify-center">
              <Link href="/" className="hover:text-gray-900">
                企業
              </Link>
              <Link href="/users" className="hover:text-gray-900">
                従業員
              </Link>
            </nav>
          </div>
        </header>
        <main className="mx-16 py-8">{children}</main>
        <Toaster richColors closeButton />
      </body>
    </html>
  );
}
